### ISSUE TITLE
Flashprint complains the 0.4 short case has errors

### ISSUE THREAD

**Issue by deece** [im-tomu/tomu-hardware#27]
No details provided, my guess is the STL fails the manifold check.

**Comment by xobs** [comment]
I don't have Flashprint, so I can't reproduce.  However, I've run that STL file through MeshFix.  Does 39df12e0c3616080f021085e6e30da3359f7ce82 solve the issue?

**Comment by deece** [comment]
Yup, that fixed it, thanks
