### ISSUE TITLE
Schematics image, but with a photo/diagram of the physical layout

### ISSUE THREAD

**Issue by micolous** [im-tomu/tomu-hardware#29]
I was having a look to see what is brought out from the EFM32HG309 on the back of the board, and so my first port of call was `/docs/tomu.pdf`.  But this shows the logical layout.  There's also no indication about which version of the board it applies to.

What would help is if there were pictures/diagrams of the actual, physical layout of the board, pointing to what each pad corresponds to on the EFM32HG309.

This would help people who are less skilled with electronics to know what they're wiring on to.

I _think_ what it is:

- The 4 pads on the top labelled with "D" and "C" are the debug interface, and, from left to right:
  1. 3.3v
  2. SWDIO
  3. SWDCLK
  4. Ground (square)
- The 4 pads on the bottom, labelled with "T" and "R" are the (Low Energy) UART interface, and, from left to right:
  1. 3.3v
  2. PB13 / LEU0_TX
  3. PB14 / LEU0_RX
  4. Ground (square)
- The four contacts on the left edge are the touch-sensitive pins, not sure what is connected to what there, but could also be repurposed for analogue or digital I/O.

**Comment by mithro** [comment]
There is some info here -> https://github.com/im-tomu/tomu-bootloader/tree/master/openocd#wiring

**Comment by mithro** [comment]
We would love for someone to create pin diagrams like those found on http://fritzing.org/parts/ or http://diwo.bq.com/pinout-uno/
