### ISSUE TITLE
Minor inconsistency in BOM documentation.

### ISSUE THREAD

**Issue by hackup** [im-tomu/tomu-hardware#32]
The README lists "1 x Capacitor >10uF 0402" under "individual parts". In the other BOM documents and links presumably the same part is listed as 4.7uF.

**Comment by xobs** [comment]
Thanks, fixed!

**Comment by hackup** [comment]
I think this is still not quite right. According to the schematics, both C1 and C2 are 1uF and C3 is 4.7uF. There doesn't seem to be a cap >10uF.

**Comment by xobs** [comment]
You're very correct.  The BOM CSV file has the correct component listing: https://github.com/im-tomu/tomu-hardware/blob/master/releases/v0.4.6/gerber/tomu-bom.csv

Fixed (again).

**Comment by hackup** [comment]
Glad to hear that because those are the components I ordered. :-) Thanks!
