### ISSUE TITLE
Test the ARM SWD

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-hardware#7]
Test that the CPU can be debugged via the ARM SWD pins using OpenOCD and GDB.

**Comment by maks** [comment]
@mithro which pads on the board are the SWD pins brought out to?
I want to have a go at using SWD with a buspirate and openocd to do the initial flashing [per this guide](https://www.earth.li/~noodles/blog/2015/08/program-fst01-with-buspirate.html).

**Comment by faemittens** [comment]
@maks C and D are the SWD pins. CLK and DIO respectively.

I screwed up the UART bootloader upgrade and then had to use OpenOCD and an STLink-v2-1 to flash the bootloader back, so I know that particular combination works. Only OpenOCD 0.10 has Happy Gecko support though. I didn't try any debugging.

**Comment by mithro** [comment]
Instructions on using ARM 2-wire with OpenOCD on a RPi are now at
https://github.com/im-tomu/tomu-bootloader/tree/master/openocd

It's definitely working, so closing this issue.
